# Generated by Django 5.0.2 on 2024-02-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('error', 'error')], default='draft', max_length=32),
        ),
    ]
