# Generated by Django 5.0.2 on 2024-02-08 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_options'),
        ('clients', '0001_initial'),
        ('sms', '0003_historicalsms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sms',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='sms',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='clients.client'),
        ),
    ]
