# Generated by Django 5.0.2 on 2024-02-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_alter_sms_campaign_alter_sms_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsms',
            name='file',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('error', 'error')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='sms',
            name='file',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('error', 'error')], default='draft', max_length=32),
        ),
    ]
