# Generated by Django 5.0.2 on 2024-02-08 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_options'),
        ('clients', '0001_initial'),
        ('sms', '0007_alter_sms_campaign_alter_sms_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsms',
            name='file',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='file',
        ),
        migrations.AlterField(
            model_name='sms',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms', to='clients.client'),
        ),
    ]
