# Generated by Django 5.0.2 on 2024-02-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_is_paused'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='is_paused',
            new_name='paused',
        ),
    ]
