# Generated by Django 5.0.2 on 2024-02-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_rename_is_paused_campaign_paused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='filter',
        ),
        migrations.AddField(
            model_name='campaign',
            name='filters',
            field=models.JSONField(default='{}', max_length=100),
        ),
    ]
